### ISSUE TITLE
Relational database implementation

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#22]
Implement the relational schema created in #24 as an SQL database using SQLite and Python. 

Make sure to add documentation to your work, because #30 will need to be able to use it when creating the user interface, and because you will likely need to be talking about your work in #34.

**Comment by zcl190002** [comment]
Python isn't a requirement.  However, if you use a programming language please use Python.

**Comment by zcl190002** [comment]
To close this issue, please provide the following screenshots.
![Image](https://github.com/user-attachments/assets/bfbba5b5-ab07-4f48-9246-14e30b25a268)

**Comment by Kash1rKhan** [comment]
Here is the link to the database file (can't directly upload a .db file)
https://drive.google.com/file/d/1-EtkFY28rEKEvI2FOuT6C-ZodFjlQYP-/view?usp=drive_link

**Comment by Kash1rKhan** [comment]
Here is the link to the Google Collab used to automate the population of the database
https://colab.research.google.com/drive/1sKfJZSw1C05wswxeaGKIqP-SNRtmmVBz?usp=sharing

**Comment by Kash1rKhan** [comment]
Here are the screenshots showing the creation of the database and sample rows for each table.

![Card_Info_sample](https://github.com/user-attachments/assets/d5031116-16d6-408c-8e5f-7b586e70e22a)
![Card_Price_sample](https://github.com/user-attachments/assets/85c101d1-288b-485c-b56a-155327d9ef83)
![Card_Print_sample](https://github.com/user-attachments/assets/085c18a3-a51a-4755-8ae0-2e9fcd9700dd)
![Commander_analytics_sample](https://github.com/user-attachments/assets/74a9a09d-dd31-4433-a6fc-f8870c886c46)
![Create_db_1](https://github.com/user-attachments/assets/0e41aef5-04ee-4d3d-9ab0-927d627499f6)
![Create_db_2](https://github.com/user-attachments/assets/200c0b10-7d16-4fe0-a83e-df6141f313ca)
![Create_db_3](https://github.com/user-attachments/assets/bb527451-880b-4017-bea5-169e52b09e5d)
![Limited_Analytics_sample](https://github.com/user-attachments/assets/b11c7843-c8a0-416e-874e-8c2bdfd3916d)

**Comment by zcl190002** [comment]
@Kash1rKhan great work!  Adding this to the report today;  will close if there are no issues.

**Comment by zcl190002** [comment]
Added to the formal report.
