### ISSUE TITLE
Relational schema diagram

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#23]
Transform the relational schema defined in #24 into a diagram.

Draw the schema diagram of your design USING A TOOL, rather than drawing manually.

**Comment by ashleytln** [comment]
![Image](https://github.com/user-attachments/assets/1f6c5431-75e0-4dde-9940-927a86410004)

Here is the image of the relational diagram I made. I used Microsoft Word to create the base of the diagram and used an online drawing tool (lucidchart.com) to draw the arrows between each relation.
