### ISSUE TITLE
Relational schema

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#24]
Use the EER model created in #26 to create a relational schema. Do not create a diagram. #23 will use this model to create the diagram.

Specify Primary Keys, Foreign Keys and referential integrity constraints in the schema.

**Comment by hrogers241** [comment]
[MTG Database Relational Schema.pdf](https://github.com/user-attachments/files/17267244/MTG.Database.Relational.Schema.pdf)

Here is the relational schema based on the EER model from last week.
Unsure if the referential integrity constraints need to be more explicit, but the primary and foreign keys are spelled out for each relation.
