### ISSUE TITLE
EER model

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#26]
Use the requirements outlined in #20 to create an EER model. Do not create a diagram, just clearly define all of the content needed to create one. #25 will convert your model into a diagram.

**Comment by dustingvyen** [comment]
[MTG EER Model Requirements.pdf](https://github.com/user-attachments/files/17173567/MTG.EER.Model.Requirements.pdf)

Here are the requirements based on the outline provided. In the outline, I wasn't 100% sure if you wanted CARD_PRINT as a weak entity of CARD_INFO. I assumed it was, so I wrote it as such, but if it is incorrect, please let me know.

@zcl190002
