### ISSUE TITLE
Dependency diagrams

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#29]
Draw a dependency diagram for each table. Must be done using a tool.
Use #38 as reference

#	Submission Requirements
Attach a PNG image of each diagram

**Comment by zcl190002** [comment]
Added requirements

**Comment by Vonkasper** [comment]
![Uploading Dependency Diagram.png…]()

**Comment by Vonkasper** [comment]
Still new to github so maybe this did not come through, if not tell me and I will rectify it in the morning.

**Comment by zcl190002** [comment]
I think that's just a hyperlink back to this page, not an image.  You need to re-upload @Vonkasper

**Comment by Vonkasper** [comment]
![Uploading Dependency Diagram.png…]()

**Comment by Vonkasper** [comment]
![Dependency Diagram](https://github.com/user-attachments/assets/9daab31d-14e1-4898-a521-98f9ff6d6455)

**Comment by Vonkasper** [comment]
Ignore previous, this last one is the completed one!

**Comment by Vonkasper** [comment]
![Dependency Diagram](https://github.com/user-attachments/assets/d5c2b2de-1118-41a4-a164-4dabc69e5af5)

**Comment by Vonkasper** [comment]
![Dependency Diagram D2](https://github.com/user-attachments/assets/92ff7789-29b8-4de0-81d2-7933253f4b05)

**Comment by Vonkasper** [comment]
> ![Dependency Diagram D2](https://private-user-images.githubusercontent.com/73517152/386915651-92ff7789-29b8-4de0-81d2-7933253f4b05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTExMTMsIm5iZiI6MTczMTgxMDgxMywicGF0aCI6Ii83MzUxNzE1Mi8zODY5MTU2NTEtOTJmZjc3ODktMjliOC00ZGUwLTgxZDItNzkzMzI1M2Y0YjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDAyMzMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYjQ3MmE2ODQ3ZDZjZDBhNjYzY2IwZTc1ZmU4NzNlZTc5ZjdjMDFhZTc0OTYxMjRmZTUxZmRkMmE1MWI2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JyJZAqkGpiB3lon_GPphqIyl50S0rCkBOkHSrrXL-jk)

Missing PK for CARD_INFO, this other version has it added otherwise this is the DDD2:
![Dependency Diagram D2(1)](https://github.com/user-attachments/assets/396e245b-cc1c-4e8c-9a7d-f81df9729963)
