### ISSUE TITLE
Relational database queries

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#36]
Kash, sorry I forgot this step during tasking.  If you don't mind taking screenshots of your database implementation in action.

![Image](https://github.com/user-attachments/assets/b6d54e4c-d239-46e0-bf52-72db025b6887)

**Comment by Kash1rKhan** [comment]
![Card_Info_Operations](https://github.com/user-attachments/assets/261e4008-2bed-4b61-93e7-7f68fb20b117)
![Card_Price_Operations](https://github.com/user-attachments/assets/ffa6c6c0-edf5-4867-a3e6-fc8728b9b2fe)
![Card_Print_Operations](https://github.com/user-attachments/assets/3c58ccd3-01d8-43ba-a9c2-b5d68fff702f)
![COMMANDER_ANALYTICS_Operations](https://github.com/user-attachments/assets/24e97062-5cf3-469d-883e-15bdf7318cda)
![LIMITED_ANALYTICS_Operations](https://github.com/user-attachments/assets/6d6e99c0-4608-459b-b318-a85864ea801d)

Here are the screenshots showing the database being able to take operations

**Comment by zcl190002** [comment]
Please close with google drive link.  Thanks!

**Comment by Kash1rKhan** [comment]
Google drive link with screenshot of test queries
https://drive.google.com/drive/folders/1fPNeQEQyhYxWuuzbY0U-5xI14jABgDd3?usp=drive_link

**Comment by zcl190002** [comment]
Re-opened for UPDATE before/after screenshots.
