### ISSUE TITLE
CREATE VIEW

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#39]
Use minimum one CREATE VIEW statement in your database to implement a view based on your specific database design. 

Please indicate what this view is for.

# Submission Requirements
Screenshot of CREATE VIEW 
Brief description of what the VIEW is for
Submit both as a comment

**Comment by Kash1rKhan** [comment]
![View](https://github.com/user-attachments/assets/ed2655e6-24eb-4a99-b6f7-9ed198600977)
