### ISSUE TITLE
Normalized implementation

### ISSUE THREAD

**Issue by zcl190002** [zcl190002/4347-007-teamMTG#40]
Normalize all your tables in your database to 3NF. 
Base your changes off #38 where applicable

**Comment by Kash1rKhan** [comment]
The database already conforms to 3NF (no transitive dependencies) so no need to normalize the database.

**Comment by zcl190002** [comment]
Not confirmed in 1NF or 2NF, but it probably doesn't matter.  Closing with no changes to the implementation.
